name: reqaize
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Your other dependencies ---
  file_picker: ^6.1.1
  http: ^1.1.0
  flutter_appauth: ^9.0.0
  shared_preferences: ^2.2.2
  read_pdf_text: ^0.3.0
  path_provider: ^2.1.2
  archive: ^3.3.8
  flex_color_scheme: ^7.3.1
  flutter_downloader: ^1.11.8 # Check compatibility/alternatives for latest Flutter
  permission_handler: ^12.0.0+1
  provider: ^6.1.2
  reorderables: ^0.6.0
  dropdown_button2: ^2.3.9
  editable: ^2.0.0
  google_fonts: ^5.1.0
  oauth2: ^2.0.1
  flutter_secure_storage: ^8.0.0
  cached_network_image: ^3.2.3
  docx_viewer: ^0.2.0
  # --- End other dependencies ---
  speech_to_text: ^6.1.0
  # Keep Syncfusion updated for SDK compatibility [4][6][7]
  syncfusion_flutter_pdf: 26.2.14
  syncfusion_flutter_core: 26.2.14
  syncfusion_flutter_charts: 26.2.14 
  #syncfusion_flutter_xlsio: ^28.1.36
  share_plus: ^10.1.4
  uuid: ^4.2.1
  super_editor: ^0.3.0-dev.20
  url_launcher: ^6.1.12
  flutter_markdown: ^0.6.17
  excel: ^4.0.6
  #flutter_pdf_text: ^0.6.0
  universal_html: ^2.2.3
  cross_file: ^0.3.3+4
  path_provider_platform_interface: ^2.1.0
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  firebase_storage_web: ^3.10.5
  animated_background: ^2.0.0
  fl_chart: ^0.69.2



  # Keep intl version and override [7]
  intl: ^0.19.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Keep the intl override [7]
dependency_overrides:
  intl: ^0.19.0



flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
